UDP
The-Mycelium-Network/webworkbook pull request #31
Opened 2022-10-04 17:35 UTC by Rico-Smit

I added UDP to the protocols

2022-10-05 04:49 UTC, bpires approved these changes
LGTM! 🎉 I'll leave my overall approval already, but I suggest we leave the blockquotes to effectively quoted text. If we use it as a matter of styling, not only we won't respect markdown semantics but we wouldn't have it when we really need to quote some text. What do you think?
Please commit the suggestions if you agree.

2022-10-05 04:49 UTC, bpires commented on content/topics/protocols/index.md
>  > SMTP stands for Simple Mail Transfer Protocol - This is an email protocol used for sending emails from one email account to another via the internet. SMTP server handles the sending, receiving, and
```suggestion
SMTP stands for Simple Mail Transfer Protocol - This is an email protocol used for sending emails from one email account to another via the internet. SMTP server handles the sending, receiving, and relaying of email. You can think of servers as your real-life post offices. When you send a letter from city A to city B, it first reaches a local post office in city A; here, it gets processed and sent to the post office in city B, which is in charge of delivering it to its final destination. The same happens with SMTP servers—though instead of taking days, the process takes a few minutes at most.
```

2022-10-05 04:49 UTC, bpires commented on content/topics/protocols/index.md
> +>UDP stands for User Datagram Protocol. It is specifically chosen for time-sensitive applications like gaming, playing videos, or Domain Name System (DNS) lookups. The UDP skips establishing an conne
```suggestion
UDP stands for User Datagram Protocol. It is specifically chosen for time-sensitive applications like gaming, playing videos, or Domain Name System (DNS) lookups. The UDP skips establishing a connection because it takes time, eliminating this step results in faster data transfer speeds, but due to the process, some of the data packets can get lost in transmission. Using UDP can leave you open to a *[DDoS attack](https://www.fortinet.com/resources/cyberglossary/ddos-attack)* if used incorrectly.
```

2022-10-05 04:53 UTC, bpires commented on content/topics/protocols/index.md
>  *[Read More Here](https://postmarkapp.com/guides/everything-you-need-to-know-about-smtp)*
```suggestion

**See also:**

* [Postmark: Everything you need to know about SMTP](https://postmarkapp.com/guides/everything-you-need-to-know-about-smtp)
```

It makes sense to me to put the title of the resource for two reasons: leave a preview of its content, and have in mind that we will probably add more resources in the future.

2022-10-08 12:19 UTC, Rico-Smit commented on content/topics/protocols/index.md
>  > SMTP stands for Simple Mail Transfer Protocol - This is an email protocol used for sending emails from one email account to another via the internet. SMTP server handles the sending, receiving, and
The ">" was added by Schalk so I think we need to leave it in.

2022-10-08 13:17 UTC, schalkneethling requested changes
Thanks, @Rico-Smit 🎉 A couple of items to address.

2022-10-08 13:17 UTC, schalkneethling commented on content/topics/protocols/index.md
> +UDP stands for User Datagram Protocol. It is specifically chosen for time-sensitive applications like gaming, playing videos, or Domain Name System (DNS) lookups. The UDP skips establishing a connect
```suggestion
UDP stands for User Datagram Protocol. UDP is specifically chosen for time-sensitive applications like online gaming, video playback, and Domain Name System (DNS) lookups. UDP uses a [connectionless communication](https://en.wikipedia.org/wiki/Connectionless_communication) model, which speeds up communication between client and server. Unlike Transmission Control Protocol(TCP), the order of packets (called datagrams) is not guaranteed, nor are there any checks to ensure packets are delivered. Because a formal connection is not made, UDP can leave one open to *[DDoS attacks](https://www.fortinet.com/resources/cyberglossary/ddos-attack)* through UDP [flood attacks](https://www.cloudflare.com/learning/ddos/udp-flood-ddos-attack/).
```

2022-10-08 14:51 UTC, bpires commented on content/topics/protocols/index.md
>  > SMTP stands for Simple Mail Transfer Protocol - This is an email protocol used for sending emails from one email account to another via the internet. SMTP server handles the sending, receiving, and
I'll add an introductory paragraph and then the verbatim, so we don't have all the paragraph unde quotes :)

2022-10-09 10:36 UTC, schalkneethling commented on content/topics/protocols/index.md
> +
Hey @Rico-Smit, thank you for the updates. I wonder, can we expand a little more on UDP here? I like this leading paragraph but maybe dig a little more into it. Just one extra paragraph will do this trick. Thanks!

2022-10-09 13:08 UTC, merged

2022-10-09 15:04 UTC, bpires commented
> Hey @Rico-Smit, thank you for the updates. I wonder, can we expand a little more on UDP here? I like this leading paragraph but maybe dig a little more into it. Just one extra paragraph will do this trick. Thanks!

@Rico-Smit don't be so eager to merge haha 😅 let's address this in a new PR 👍🏻

2022-10-09 15:55 UTC, Rico-Smit commented
Hey @bpires  i had a thing or two to add today thags why i approved it, i will add some more yes and i want to add my FTP as well. I will adress these 2 together then