Edited titles of topic pages
The-Mycelium-Network/webworkbook pull request #36
Opened 2022-10-08 13:05 UTC by bharmalh

Removed the "- web://workbook" part from all the index.md files within the topics folder as it is already being appended during site generation.

2022-10-08 14:57 UTC, schalkneethling requested changes
Thanks, @bharmalh - Just one item to address.

2022-10-08 14:57 UTC, schalkneethling commented on content/topics/protocols/index.md
> +> _[Read More Here](https://postmarkapp.com/guides/everything-you-need-to-know-about-smtp)_
Was this intentional? It changes it from a bulleted list to an emphasized block quote.

2022-10-08 14:59 UTC, bharmalh commented on content/topics/protocols/index.md
> +> _[Read More Here](https://postmarkapp.com/guides/everything-you-need-to-know-about-smtp)_
No, this was not intentional. Sorry about that.

2022-10-10 23:07 UTC, schalkneethling commented on content/topics/protocols/index.md
> +> _[Read More Here](https://postmarkapp.com/guides/everything-you-need-to-know-about-smtp)_
```suggestion
- [Read More about SMTP](https://postmarkapp.com/guides/everything-you-need-to-know-about-smtp)
```

2022-10-10 23:07 UTC, schalkneethling commented on content/topics/protocols/index.md
> +> _[Read More Here](https://postmarkapp.com/guides/everything-you-need-to-know-about-smtp)_
No worries, I have reverted the change.

2022-10-10 23:09 UTC, schalkneethling approved these changes
Thank you for your contribution, @bharmalh 🎉

2022-10-10 23:09 UTC, merged