Adding updated What is Git? index.md file
The-Mycelium-Network/webworkbook pull request #42
Opened 2022-10-10 00:48 UTC by CoyaG

This is the full first draft of What is Git?

2022-10-10 03:57 UTC, bpires commented on content/topics/what-is-git/index.md
> +title: What is Git? - web://workbook
```suggestion
title: What is Git?
```

Remove '- web://workbook' as it is already appended by HUGO

2022-10-10 04:28 UTC, bpires requested changes
Hi @CoyaG, great work! You seem to have a way with words. I loved how you told the history of Git, and you gathered some very interesting resources. Kudos 🎉 

The two changes I suggested were mostly related to the markdown use, so we maintain a pattern throughout the project, as well as respect the markup language standards.

If you agree with the suggestions, you can commit the changes directly by hitting “commit suggestions”. If not, please speak your mind, and we go on from there. 😉 

About the Git/GitHub issue, I think it's better to have some input from @schalkneethling first.

2022-10-10 04:28 UTC, bpires commented on content/topics/what-is-git/index.md
> +* [git-game-2](https://github.com/git-game/git-game-v2)
```suggestion
Need help? Git can be quite the learning curve. Below are some resources to help get you started.

* [Git Tutorial for Beginners: Learn Git in 1 Hour](https://www.youtube.com/watch?v=8JJ101D3knE&ab_channel=ProgrammingwithMosh): This hour-long video walks brand new beginners through the basics of git, starting with the setup.
* [Git Cheatsheet](https://about.gitlab.com/images/press/git-cheat-sheet.pdf): This is a short pdf file from GitLab with some basic Git commands and a brief explanation of each.
* [50 Git Commands](https://www.freecodecamp.org/news/git-cheat-sheet/): 50 Git commands with brief explanations
* [Dangit, Git!?!](https://dangitgit.com/en): Git got ya down? Mess up? We’ve all been there. This guide helps you get back into the flow (and keeps you from panicking) by helping you fix some common Git mistakes.

Feeling adventurous? Play these games to practice using Git! 

* [git-game](https://github.com/git-game/git-game)
* [git-game-2](https://github.com/git-game/git-game-v2)
  
```

It's important to respect markdown specs. We should use the `*` only for unordered list items. I guess this way (the item + its description), we can list the resources without taking too much space or breaking the list continuity. What do you think?

2022-10-10 04:28 UTC, bpires commented on content/topics/what-is-git/index.md
> +* git-scm.com gives an overall explanation about how Git works.
```suggestion
**See also:**

* [Git vs GitHub: What's the difference?](https://www.youtube.com/watch?v=wpISo9TNjfU&ab_channel=IBMTechnology): This video briefly discusses the difference between Git and GitHub/GitLab.
* [Getting Started - What is Git?](https://www.git-scm.com/book/en/v2/Getting-Started-What-is-Git%3F): Git official documentation gives an overall explanation of how it works.
```

- suggestion to use `<ul>` (we will most likely add more resources later).
- putting a call to indicate what type of resources ("see also" → complementary resources)
- git-scm is the Git per se, so it's better if we can call it "Git documentation"

2022-10-10 04:28 UTC, bpires commented on content/topics/what-is-git/index.md
> +Git is a distributed version control system (DVCS) that allows you to create a local copy of a remote repository. Creating a local copy enables you to create changes without interfering with original
I think we could discuss the last sentence a little bit.

There are several GUI Clients to use Git nowadays (it also comes with a built-in one), so I would argue that a terminal is no longer required to use it, although it remains the most common tool.

Also, I think putting Git side by side with GitHub/GitLab for comparison could be a little confusing. The way I see it, GitHub and its peers are tools built on top of Git that have different purposes. 

They are related, for sure, but I don't know if it's accurate to say that GitHub is a “web-hosted version of Git”. Perhaps, we can state that GitHub/GitLab are platforms for hosting Git repositories, so they can be used collaboratively.

Btw, I liked very much the video resource, and it clarifies it, but the sentence alone can be a little misleading. I think we might want to hear @schalkneethling guidance on this.

2022-10-10 16:33 UTC, CoyaG commented on content/topics/what-is-git/index.md
> +* [git-game-2](https://github.com/git-game/git-game-v2)
I agree. I was not sure exactly which type of format was needed, so I just typed out what made sense at the time.

2022-10-10 16:36 UTC, CoyaG commented on content/topics/what-is-git/index.md
> +Git is a distributed version control system (DVCS) that allows you to create a local copy of a remote repository. Creating a local copy enables you to create changes without interfering with original
Okay, no problem waiting for @schalkneethling input. I will commit the other suggestions and hold off on this one until further review.

2022-10-13 16:15 UTC, schalkneethling commented
@CoyaG seeing that you added https://github.com/The-Mycelium-Network/webworkbook/pull/42/commits/8a4db3a8f46dfc8c16f13be3cc07ab530e2ae66f and https://github.com/The-Mycelium-Network/webworkbook/pull/42/commits/1d07b87035b5d1e95b0bfd58e03a613041644827, do we still need this PR? https://github.com/The-Mycelium-Network/webworkbook/pull/53

2022-10-13 16:24 UTC, schalkneethling reviewed
This is a great write-up 🎉 Thank you, @CoyaG. Just a few suggestions from my side.

2022-10-13 16:24 UTC, schalkneethling commented on content/topics/what-is-git/index.md
> +keywords: git, github, git explained
```suggestion
keywords: git, git 101, git explained

```

2022-10-13 16:24 UTC, schalkneethling commented on content/topics/what-is-git/index.md
> +## So, What is Git?
```suggestion
## So, what is Git?

```

2022-10-13 16:24 UTC, schalkneethling commented on content/topics/what-is-git/index.md
> +Git is a distributed version control system (DVCS) that allows you to create a local copy of a remote repository. Creating a local copy enables you to create changes without interfering with original
There are also GUIs available that would be worth mentioning:
https://git-scm.com/downloads/guis

2022-10-13 16:24 UTC, schalkneethling commented on content/topics/what-is-git/index.md
> +Fun fact! According to a [2022 Developer Survey from Stack Overflow](https://survey.stackoverflow.co/2022/#section-version-control-version-control-systems), just under 97% of professional developers
Nice!

2022-10-13 16:24 UTC, schalkneethling commented on content/topics/what-is-git/index.md
> +In 2002, the Linux kernel community began using BitKeeper (developed by BitMover), which was a proprietary DVCS. In order for the community to use this paid software for free, there were limitations.
It would be nice to link to Bitkeep and BitMover if they are still around.

2022-10-13 16:24 UTC, schalkneethling commented on content/topics/what-is-git/index.md
> +* [Git Tutorial for Beginners: Learn Git in 1 Hour](https://www.youtube.com/watch?v=8JJ101D3knE&ab_channel=ProgrammingwithMosh): This hour-long video walks brand new beginners through the basics of g
```suggestion
* [Git Tutorial for Beginners: Learn Git in 1 Hour](https://www.youtube.com/watch?v=8JJ101D3knE&ab_channel=ProgrammingwithMosh): This video walks beginners through the basics of Git, starting with the setup.

```

2022-10-13 16:24 UTC, schalkneethling commented on content/topics/what-is-git/index.md
> +* [Git Cheatsheet](https://about.gitlab.com/images/press/git-cheat-sheet.pdf): This is a short pdf file from GitLab with some basic Git commands and a brief explanation of each.
```suggestion
* [Git Cheatsheet (PDF Download - 86KB)](https://about.gitlab.com/images/press/git-cheat-sheet.pdf): This is a short PDF file from GitLab with some basic Git commands and a brief explanation of each.
```

Thank you for calling out that this is a PDF 👍  Generally, it is also good to add it to the link text and include the size of the PDF)

2022-10-13 22:21 UTC, schalkneethling commented on content/topics/what-is-git/index.md
> +Git is a distributed version control system (DVCS) that allows you to create a local copy of a remote repository. Creating a local copy enables you to create changes without interfering with original
> They are related, for sure, but I don't know if it's accurate to say that GitHub is a “web-hosted version of Git”. Perhaps, we can state that GitHub/GitLab are platforms for hosting Git repositories, so they can be used collaboratively.

Hey everyone, thank you for having this fruitful discussion. I like your comparison in the quoted text above, @bpires. I reckon we can go with that.

2022-10-13 23:08 UTC, CoyaG commented on content/topics/what-is-git/index.md
> +Git is a distributed version control system (DVCS) that allows you to create a local copy of a remote repository. Creating a local copy enables you to create changes without interfering with original
I will look into this.

2022-10-13 23:08 UTC, CoyaG commented on content/topics/what-is-git/index.md
> +In 2002, the Linux kernel community began using BitKeeper (developed by BitMover), which was a proprietary DVCS. In order for the community to use this paid software for free, there were limitations.
I will look into this.

2022-10-13 23:11 UTC, CoyaG commented on content/topics/what-is-git/index.md
> +* [Git Cheatsheet](https://about.gitlab.com/images/press/git-cheat-sheet.pdf): This is a short pdf file from GitLab with some basic Git commands and a brief explanation of each.
Gotcha

2022-10-17 04:09 UTC, bpires commented on content/topics/what-is-git/index.md
> +In 2002, the Linux kernel community began using BitKeeper (developed by BitMover), which was a proprietary DVCS. In order for the community to use this paid software for free, there were limitations.
```suggestion
In 2002, the Linux kernel community began using [BitKeeper](http://www.bitkeeper.org/)(developed by BitMover), which was a proprietary DVCS. In order for the community to use this paid software for free, there were limitations. BitMover would control metadata, as well as disallow Linux developers to be involved in competing revision control projects while using BitKeeper. This relationship ended when Andrew Tridgell reverse-engineered BitKeeper. BitMover was not happy about this.

```

2022-10-17 04:24 UTC, bpires commented on content/topics/what-is-git/index.md
> +Torvalds decided to figure out another solution. In 2005, Git was born! Since its creation, a community of developers have continued to improve and maintain the project.
```suggestion
Torvalds decided to figure out another solution. In 2005, Git was born! Since its creation, a community of developers has continued to improve and maintain the project. BitKeeper, on the other hand, [went open source in 2016](https://lwn.net/Articles/686986/), after more than a decade of trying to maintain relevance in the shadow of Git.

```

2022-10-17 04:55 UTC, bpires commented on content/topics/what-is-git/index.md
> +Git is a distributed version control system (DVCS) that allows you to create a local copy of a remote repository. Creating a local copy enables you to create changes without interfering with original
```suggestion
Git is a free and open-source Distributed Version Control System (DVCS). It allows tracking changes in any set of files with speed and efficiency. Git supports multiple local branches that can be entirely independent of each other. Creating a local copy enables you to work on changes without interfering with the original project files. Git is great for collaborations, offline work, or even branching off with new or risky ideas. 

Most developers use Git from the command line, but plenty of modern IDE's come with Git integrations (like [VSCode](https://code.visualstudio.com/docs/sourcecontrol/overview), for instance), as well as there are a lot of [GUI tools for users looking for platform-specific experience](https://git-scm.com/downloads/guis/).

There are also many platforms for hosting Git repositories, so they can be used collaboratively over the internet, such as [GitHub](https://github.com/), [GitLab](https://about.gitlab.com/) and [BitBucket](https://bitbucket.org/).

```

2022-10-17 04:56 UTC, bpires approved these changes

2022-10-17 04:57 UTC, bpires requested changes
@schalkneethling and @CoyaG please check the last suggestions I've made and, if you agree, I think this PR is good to go.

2022-10-18 00:16 UTC, CoyaG commented
Looks great!

2022-10-22 19:13 UTC, bpires commented on content/topics/what-is-git/index.md
> +## How to use Git
```suggestion
### How to use Git

```

2022-10-22 19:14 UTC, bpires commented on content/topics/what-is-git/index.md
> +
```suggestion
### History of Git

The creation of Git is an interesting story which holds its origins within the Linux kernel community. Between 1991-2002, changes made to Linux were passed around as patches and archived files; developers even mailed code to one another using disks or flash drives. The creator of Linux, Linus Torvalds, needed to apply these changes to his own source tree. Because of this, the only way to see a history of changes was to compare the large files between releases. 

In 2002, the Linux kernel community began using [BitKeeper](http://www.bitkeeper.org/) (developed by BitMover), which was a proprietary DVCS. In order for the community to use this paid software for free, there were limitations. BitMover would control metadata, as well as disallow Linux developers to be involved in competing revision control projects while using BitKeeper. This relationship ended when Andrew Tridgell reverse-engineered BitKeeper. BitMover was not happy about this.

Torvalds decided to figure out another solution. In 2005, Git was born! Since its creation, a community of developers has continued to improve and maintain the project. BitKeeper, on the other hand, [went open source in 2016](https://lwn.net/Articles/686986/), after more than a decade of trying to maintain relevance in the shadow of Git.

```

2022-10-22 19:15 UTC, merged