I am adding FTP
The-Mycelium-Network/webworkbook pull request #50
Opened 2022-10-11 19:43 UTC by Rico-Smit

I am adding FTP

2022-10-12 14:02 UTC, bpires requested changes
I suggested some changes in the text and in the way we organize references. If you agree, I think we are good to merge.

2022-10-12 14:02 UTC, bpires commented on content/topics/protocols/index.md
> +* [FTP-Hostinger] (https://www.hostinger.com/tutorials/what-is-ftp)
```suggestion
- [MDN Web Docs Glossary: FTP](https://developer.mozilla.org/en-US/docs/Glossary/FTP)

**See also:**

- [Hostinger Tutorials: What is FTP - FTP Explained for Beginners](https://www.hostinger.com/tutorials/what-is-ftp)
- Videos:
  - [CertBros: FTP Explained | File Transfer Protocol | Cisco CCNA 200-301](https://www.youtube.com/watch?v=L9aZpg0ip70)
```

2022-10-13 14:39 UTC, schalkneethling commented
@Rico-Smit Let me know once you have had a chance to look at @bpires' review comments. Thanks!

2022-10-13 14:58 UTC, Rico-Smit commented
> @Rico-Smit Let me know once you have had a chance to look at @bpires' review comments. Thanks!

I have reviewed what i can from my moblie device, i will be working tonight if something is missing or needs doing

2022-10-14 16:13 UTC, bpires commented
What happened @Rico-Smit? I think you accidentally closed the PR.

2022-10-14 16:54 UTC, Rico-Smit commented
> What happened @Rico-Smit? I think you accidentally closed the PR.

It seems I deleted the branch by accident, I restored it now.

2022-10-14 19:35 UTC, merged