Different types of internet connections
The-Mycelium-Network/webworkbook pull request #56
Opened 2022-10-14 14:21 UTC by carinadiesel-dev

Different types of internet connections

Part of #25

2022-10-20 13:34 UTC, bpires commented on content/topics/types-of-connections/index.md
> +description: A collection of informational pieces that explains different types of internet connection.
```suggestion
description: A collection of informational pieces that explain different types of internet connections.
```

2022-10-20 13:36 UTC, bpires commented on content/topics/types-of-connections/index.md
> +A dial-up connection is established when two or more communication devices use a public switched telephone network (PSTN) to connect to an Internet service provider (ISP) at data transfer rates (DTR)
```suggestion
According to [Techopedia](https://www.techopedia.com/definition/25953/dial-up-connection), a dial-up connection is established when two or more communication devices use a public switched telephone network (PSTN) to connect to an Internet Service Provider (ISP) at Data Transfer Rates (DTR) of 56kbps, 
```

2022-10-20 13:37 UTC, bpires commented on content/topics/types-of-connections/index.md
> +_Listen to the sound of a dial up connection_
```suggestion
_Listen to the sound of a dial-up connection_
```

2022-10-20 13:39 UTC, bpires commented on content/topics/types-of-connections/index.md
> +{{< youtube id="gsNaR6FRuO0" title="Listen to the sound of a dial up connection" >}}
```suggestion
{{< youtube id="gsNaR6FRuO0" title="Listen to the sound of a dial-up connection." >}}
```

2022-10-20 13:40 UTC, bpires commented on content/topics/types-of-connections/index.md
> +[Computer Hope](https://www.computerhope.com/jargon/d/dialup.htm)
```suggestion
### More Resources

[Computer Hope: Dial-up](https://www.computerhope.com/jargon/d/dialup.htm)
```

2022-10-20 13:43 UTC, bpires commented on content/topics/types-of-connections/index.md
> +[Understanding Broadband Internet Speeds](https://www.lifewire.com/broadband-internet-speeds-explained-437202)
```suggestion
### More info

[Lifewire: Understanding Broadband Internet Speeds](https://www.lifewire.com/broadband-internet-speeds-explained-437202)
```

2022-10-20 13:47 UTC, bpires commented on content/topics/types-of-connections/index.md
> +## Broadband includes several types of high-speed internet technologies such as:
```suggestion

Broadband includes several types of high-speed internet technologies such as:
```

2022-10-20 13:47 UTC, bpires commented on content/topics/types-of-connections/index.md
> +# Fiber
```suggestion
## Fiber
```

2022-10-20 13:47 UTC, bpires commented on content/topics/types-of-connections/index.md
> +# DSL
```suggestion
## DSL
```

2022-10-20 13:48 UTC, bpires commented on content/topics/types-of-connections/index.md
> +# Cable
```suggestion
## Cable
```

2022-10-20 13:48 UTC, bpires commented on content/topics/types-of-connections/index.md
> +# Satellite
```suggestion
## Satellite
```

2022-10-20 13:48 UTC, bpires commented on content/topics/types-of-connections/index.md
> +# Wireless
```suggestion
## Wireless
```

2022-10-20 13:48 UTC, bpires commented on content/topics/types-of-connections/index.md
> +# Cellular
```suggestion
## Cellular
```

2022-10-20 13:48 UTC, bpires commented on content/topics/types-of-connections/index.md
> +## (EDGE, 3G, H+, 4G, 5G)
```suggestion
### (EDGE, 3G, H+, 4G, 5G)
```

2022-10-20 13:51 UTC, bpires commented on content/topics/types-of-connections/index.md
> +_Still curious about fibre ? Read more_ [here](https://www.explainthatstuff.com/fiberoptics.html)
```suggestion
_Still curious about fiber? [Read more about it here](https://www.explainthatstuff.com/fiberoptics.html)_
```

2022-10-20 13:54 UTC, bpires commented on content/topics/types-of-connections/index.md
> +DSL (Digital Subscriber Line) operates over standard copper telephone lines like dial-up service but is many times faster than dial-up. In addition, unlike dial-up, DSL does not tie up the phone line
```suggestion
According to [Easy Tech Junkie](https://www.easytechjunkie.com/what-is-dsl.htm), DSL (Digital Subscriber Line) operates over standard copper telephone lines like dial-up service but is many times faster than dial-up. In addition, unlike dial-up, DSL does not tie up the phone line. Coexisting with telephone service in this way allows users to surf the Net and use the phone at the same time.
```

2022-10-20 13:58 UTC, bpires commented on content/topics/types-of-connections/index.md
> +_To learn more about DSL,_ [click here](https://www.lifewire.com/different-types-of-dsl-technology-817522)
```suggestion
There are two types of DSL, namely Asymmetric DSL (ADSL) and Symmetric DSL (SDSL). _Learn more about the [different types of DSL technology here](https://www.lifewire.com/different-types-of-dsl-technology-817522)_.
```

2022-10-20 14:01 UTC, bpires commented on content/topics/types-of-connections/index.md
> +Unlike land-based internet services like DSL, fibre or cable which received its signal from cables either below or slightly above the ground, satellite internet is a wireless connection beamed down f
```suggestion
Unlike land-based internet services like DSL, fiber or cable, which receive its signal from cables either below or slightly above the ground, satellite internet is a wireless connection beamed down from satellites orbiting the earth.
```

2022-10-20 14:05 UTC, bpires commented on content/topics/types-of-connections/index.md
> +_Signal boosters go into much more details regarding wifi standards,types of wifi and much more_ [here](https://www.signalboosters.com/blog/what-is-wifi-and-how-does-it-work/)
```suggestion
_Understand what WiFi is and how it really works in [this article by Signal boosters](https://www.signalboosters.com/blog/what-is-wifi-and-how-does-it-work/)_.
```

2022-10-20 16:15 UTC, bpires requested changes
Hey @carinadiesel-dev, congrats on your write-up on such a broad subject! 🎉 

I went on and already done a proofread, fixed some typos and style issues. Please re-read everything and change what you think it's necessary. 

Also, I reorganized the heading levels. Please note that Markdown/HTML heading best practices requests that we nest different heading levels hierarchically.

> Headings with an equal or higher rank start a new section, headings with a lower rank start new subsections that are part of the higher ranked section. Skipping heading ranks can be confusing and should be avoided where possible: Make sure that a `<h2>` is not followed directly by an `<h4>`, for example. 

Regarding the content, it seems good to me, but I have some concerns about references and originality.

I have to say I'm not a fan of using "according to.." so frequently, and, when using it, please note that, if you are mentioning the source text verbatim, you still have to put it between quotes. In that note, I think it's better to paraphrase the content, and the cite the sources as "references". Let me know what you think about it.

IMO, the best approach is to do a quick definition and then point to resources, like articles or videos, for more in-depth knowledge. When working with definitions sites like Wikipedia and alike are a good point to start. I like those references for the main content because Wikipedia (or MDN, for instance) is more unlikely to get outdated, be discontinued or go offline. For the "more resources", we can link to articles scattered on the internet and then, if they went offline, we will fix it.

Also, take a look at the images issues I pointed out. You should consider if it's really relevant to embed it. If so, fix the syntax and always reference the source. 

There's also an image on the repo (`speed-chart.png"`) that, unless I'm mistaken, it's not referenced anywhere in the text. Please take a look into it!

Remember, to continue working on this PR, just add new commits by pushing to the `25-how-is-data-sent-over-the-internet` branch on your fork.

2022-10-22 14:10 UTC, schalkneethling commented
Wow, thank you for the detailed review, @bpires 🙌

2022-10-22 14:14 UTC, schalkneethling commented
@carinadiesel-dev let me know when you have had a moment to address the review comments. I would be happy to do a second round of review but, I do not want to overwhelm you. Thanks!

2022-11-08 17:53 UTC, schalkneethling commented
@carinadiesel-dev I believe this https://github.com/The-Mycelium-Network/webworkbook/pull/74 is a duplicate? Have a look at my comments there and apply them here. At that point, I would suggest closing the other one and keeping this one. Thanks!

2022-11-20 14:59 UTC, bpires commented
> @carinadiesel-dev I believe this #74 is a duplicate? Have a look at my comments there and apply them here. At that point, I would suggest closing the other one and keeping this one. Thanks!

I think this one got mixed up with #74, which should be **just** about HTTP and HTTPS, but had the part of "types-of-connections" as well (the subject of this PR). Probably because @carinadiesel-dev did #74 directly on the main branch of her fork. Maybe we should draft up a step-by-step of the workflow when working in different PRs, because it gets confusing sometimes.

2022-12-05 23:04 UTC, schalkneethling commented
Ping 🔔  @carinadiesel-dev when you have a moment. Thanks!

2022-12-19 22:26 UTC, schalkneethling commented
@carinadiesel-dev we are going to merge this one and then iterate on improving and cleaning up. Thanks!

2022-12-19 22:27 UTC, merged