adding DNS to the protocols
The-Mycelium-Network/webworkbook pull request #58
Opened 2022-10-15 16:46 UTC by BlackNinjaCat86

2022-10-17 00:48 UTC, schalkneethling requested changes
Thank you for your contribution, @BlackNinjaCat86 🐈  A couple of items to address. I think it will also be nice to embed this video just below the title:

https://www.youtube.com/watch?v=5o8CwafCxnU&t=2s

Let me know what you think.

2022-10-17 00:48 UTC, schalkneethling commented on content/topics/protocols/index.md
> +The caching server only performs cached-query services.
This sounds like a list:

```suggestion
 * The primary server is used for all administrative tasks.
* The secondary is the backup server.
* The caching server only performs cached-query services.
```

2022-10-17 00:48 UTC, schalkneethling commented on content/topics/protocols/index.md
> +* [Microsoft](https://learn.microsoft.com/en-us/windows/win32/dns/dns-servers)
Need to remove the empty lines or else each item becomes its own list:

```suggestion
* [How DNS Works](https://howdns.works/ep1/)
* [NS1](https://ns1.com/resources/what-is-dns)
* [Microsoft](https://learn.microsoft.com/en-us/windows/win32/dns/dns-servers)
```

2022-10-22 14:29 UTC, schalkneethling requested changes
This looks good, @BlackNinjaCat86 🌮 One more suggestion and we should be good to go.

2022-10-22 14:29 UTC, schalkneethling commented on content/topics/protocols/index.md
> +{{< youtube id="5o8CwafCxnU&t=2s" title="Explaining: IP Addresses & DNS" >}}
I have been thinking about this, and it might be good to make the titles something like:

```suggestion
{{< youtube id="5o8CwafCxnU&t=2s" title="A video explaining IP addresses and DNS" >}}
```

Essentially imagine how a screen reader might read this title to the end-user.

2022-10-22 14:45 UTC, BlackNinjaCat86 commented
@schalkneethling All changes made 😄

2022-10-24 22:19 UTC, bpires commented on content/topics/protocols/index.md
> +A standard protocol that works like a phonebook - it manages the mapping between names (websites) and numbers (IP addresses). This means that you don't need to remember complicated IP addresses, beca
```suggestion
A standard protocol that works like a phonebook - it manages the mapping between names (websites) and numbers (IP addresses). This means that you don't need to remember complicated IP addresses, because DNS translates your domain name (URL) to the corresponding address. There are 3 types of DNS servers, namely: primary, secondary and caching servers. 
```

2022-10-24 22:22 UTC, bpires commented on content/topics/protocols/index.md
> +*The caching server only performs cached-query services.
```suggestion
* The primary server is used for all administrative tasks.
* The secondary is the backup server.
* The caching server only performs cached-query services.
```

@BlackNinjaCat86 note that if you don't add the space, it will not render as an unordered list.

2022-10-24 22:22 UTC, bpires commented on content/topics/protocols/index.md
> +**Refrances**
```suggestion
**References**
```

2022-10-24 22:28 UTC, bpires commented on content/topics/protocols/index.md
> +* [Microsoft](https://learn.microsoft.com/en-us/windows/win32/dns/dns-servers)
```suggestion
* [DNSimple: How DNS Works](https://howdns.works/)
* [NS1: What is DNS? DNS Explained](https://ns1.com/resources/what-is-dns)
* [Microsoft Learn: DNS Servers](https://learn.microsoft.com/en-us/windows/win32/dns/dns-servers)
```

I think it is essential to provide some information on the resources listed, so the reader doesn't have to click on them to know what they are about. For me, `[author]:[title]` is a good minimum approach.

2022-10-24 22:32 UTC, bpires requested changes
Hey @BlackNinjaCat86! 

I left some comments with suggestions, if you agree with them, just click `Commit suggestion` on each one, or gather all of them by clicking `Add suggestion to batch` and them `Commit suggestions` on the top. 

If not, just ping me in your comments, and we'll discuss them in detail.  

You really did a great job, these are all just small details! 🎉

2022-10-29 15:16 UTC, schalkneethling commented
Hey @BlackNinjaCat86, friendly ping. If you need any help with this one, please let us know. Thanks!

2022-10-29 15:21 UTC, BlackNinjaCat86 commented
@bpires thanx, will have a look as soon as I am on my pc 🙂 Unfortunately didnt get the notifications.

2022-10-30 18:15 UTC, BlackNinjaCat86 commented
@bpires thanks for the assistance 😸

2022-10-30 22:21 UTC, merged