Added content about web browsers
The-Mycelium-Network/webworkbook pull request #59
Opened 2022-10-15 18:03 UTC by bharmalh

I added a new topic called "What is a web browser" and added content and resources to it. Will really appreciate any feedback.

2022-10-22 13:57 UTC, schalkneethling requested changes
Thank you, @bharmalh for this excellent write up. My apologies for having taken so long to get back to you. I have made some suggestions for you to consider.

2022-10-22 13:57 UTC, schalkneethling commented on content/topics/what-is-a-web-browser/index.md
> +description: A collection of informational pieces that explains what web browsers are and their different types.
```suggestion
description: An informational page that explains what web browsers are and the difference between the types of browsers on the market.
```

2022-10-22 13:57 UTC, schalkneethling commented on content/topics/what-is-a-web-browser/index.md
> +For example, when you type in 'www.google.com' and hit enter, the browser gets the necessary files (HTML, CSS, Javascript, Images and more) from Google's servers and paints up the page (rendering) wh
Let's. "promote" one of the more privacy-centric websites out there :)

```suggestion
For example, when you type in 'www.duckduckgo.com' and hit enter, the browser gets the necessary files (HTML, CSS, Javascript, Images, and more) from DuckDuckGo's servers, combines, parses, and renders (or paints) the page with which you can then interact with.
```

2022-10-22 13:57 UTC, schalkneethling commented on content/topics/what-is-a-web-browser/index.md
> +This article breaks down the different parts and features of a browser with simple explanations and images: [Internet Basics - Using a Web Browser](https://edu.gcfglobal.org/en/internetbasics/using-a
I think the links need to be like this.

```suggestion
This article breaks down the different parts and features of a browser with simple explanations and images: [Internet Basics - Using a Web Browser](https://edu.gcfglobal.org/en/internetbasics/using-a-web-browser/1/)
```

It would also be neat to embed the video directly on our page; what do you think?

```
{{< youtube id="FxirRVJWUTs" title="A video introduction to browser basics" >}}
```

2022-10-22 13:57 UTC, schalkneethling commented on content/topics/what-is-a-web-browser/index.md
> +This article breaks down the different parts and features of a browser with simple explanations and images: [Internet Basics - Using a Web Browser](https://edu.gcfglobal.org/en/internetbasics/using-a
Also, I think we can just link to the page. Something like:

```suggestion
* Internet Basics - Using a Web Browser](https://edu.gcfglobal.org/en/internetbasics/using-a-web-browser/1/ "Internet Basics - Using a Web Browser")
```

2022-10-22 13:57 UTC, schalkneethling commented on content/topics/what-is-a-web-browser/index.md
> +Chromium is a free and open-source browser, which means that the code used to create it is freely available and written by contributors. Then, different groups/people can play with it and shape it to
```suggestion
Chromium is a free and open-source browser, which means that the source code used to create it is freely available and written by contributors. Because of its open-source nature, anyone can contribute to the Chromium project or, create a fork (copy) of the project to create their own version of the browser.
```

2022-10-22 13:57 UTC, schalkneethling commented on content/topics/what-is-a-web-browser/index.md
> +Chromium is a free and open-source browser, which means that the code used to create it is freely available and written by contributors. Then, different groups/people can play with it and shape it to
It would also be good to link to the Chromium project page here.

2022-10-22 13:57 UTC, schalkneethling commented on content/topics/what-is-a-web-browser/index.md
> +The most popular example of a chromium-based browser is [Google Chrome](https://www.google.com/chrome/ "Google Chrome"). However, a lot of other browsers today are built on top of Chromium, including
I believe we should also use a capital letter when referring to Chromium.

2022-10-22 13:57 UTC, schalkneethling commented on content/topics/what-is-a-web-browser/index.md
> +The most popular example of a chromium-based browser is [Google Chrome](https://www.google.com/chrome/ "Google Chrome"). However, a lot of other browsers today are built on top of Chromium, including
Would also be nice to link to those various browsers.

2022-10-22 13:57 UTC, schalkneethling commented on content/topics/what-is-a-web-browser/index.md
> +One major advantage of using Chromium-based browsers is that extensions that work with Google Chrome work with them too!
Web extensions have become a standard, and as such extensions generally now work across all browsers. With that in mind, I feel that we should remove this sentence.

2022-10-22 13:57 UTC, schalkneethling commented on content/topics/what-is-a-web-browser/index.md
> +To understand more about chromium you can read this [article by LifeWire](https://www.lifewire.com/chromium-web-browser-4171288 "article byLifeWire").
```suggestion
### Additional reading

* [Chromium source on GitHub](https://github.com/chromium/chromium)
* [Chromium explained on Wikipedia](https://en.wikipedia.org/wiki/Chromium_(web_browser))
* [Deep dive video on the difference between Chrome and Chromium](https://www.youtube.com/watch?v=xxuioJkc0J8)
```

2022-10-22 13:57 UTC, schalkneethling commented on content/topics/what-is-a-web-browser/index.md
> +WebKit is the browser engine used mainly by the Safari Browser as well as many other apps on macOS, iOS and Linux. A browser engine is a core part of every major browser responsible for converting HT
```suggestion
WebKit is the browser engine used mainly by Safari. Webkit is maintained by Apple computers and mainly used by the Safari web browser. A browser engine is a core part of every major browser responsible for converting HTML and other resources into what you see on your screen.
```

2022-10-22 13:57 UTC, schalkneethling commented on content/topics/what-is-a-web-browser/index.md
> +Safari is the major browser on all Apple devices including iPhones, iPads and Macs. You might also be surprised to know that, right now, all browsers on iOS use Safari as their rendering engine. This
I believe that when referring to Safari on mobile devices, one should always state Safari on iOS.

2022-10-22 13:57 UTC, schalkneethling commented on content/topics/what-is-a-web-browser/index.md
> +Safari is the major browser on all Apple devices including iPhones, iPads and Macs. You might also be surprised to know that, right now, all browsers on iOS use Safari as their rendering engine. This
We could also mention that Webkit is open source.

2022-10-22 13:57 UTC, schalkneethling commented on content/topics/what-is-a-web-browser/index.md
> +Mozilla Firefox is a free and open-source browser developed by the Mozilla Foundation. At its core is the Gecko browser engine similar to WebKit for Safari as mentioned above.
The last part of this sentence might cause a bit of confusion. I would rephrase it like this:

```suggestion
Mozilla Firefox is a free and open-source browser developed by the Mozilla Foundation. As mentioned, Safari browsers use the Webkit rendering engine. What we did not mention is that Chromium-based browsers use a fork of Webkit called Blink. At the core of the Firefox browser is the Gecko rendering engine as well as component of the [Servo](https://servo.org/) engine.
```

2022-10-22 13:57 UTC, schalkneethling commented on content/topics/what-is-a-web-browser/index.md
> +This [FAQ](https://www.mozilla.org/en-US/firefox/faq/) from Mozilla provides answers to some common questions about the browser.
I would combine these into a single paragraph.

2022-10-22 13:57 UTC, schalkneethling commented on content/topics/what-is-a-web-browser/index.md
> +{{< youtube 4Q7FTjhvZ7Y >}}
We should always use the following form of the Youtube shortcode for [accessibility reasons](https://dequeuniversity.com/tips/provide-iframe-titles):

```
{{< youtube id="4Q7FTjhvZ7Y" title="Code Rush, a short documentary about the birth of the Mozilla project." >}}
```

2022-10-23 08:52 UTC, bharmalh commented on content/topics/what-is-a-web-browser/index.md
> +For example, when you type in 'www.google.com' and hit enter, the browser gets the necessary files (HTML, CSS, Javascript, Images and more) from Google's servers and paints up the page (rendering) wh
Just a small grammatical suggestion. I think the last word 'with' needs to be removed.

2022-10-23 09:01 UTC, bharmalh commented on content/topics/what-is-a-web-browser/index.md
> +One major advantage of using Chromium-based browsers is that extensions that work with Google Chrome work with them too!
But firefox extensions are not compatible with Chromium-based browsers. I wanted to mention it to show the relationship and benefits that all these browsers have because of their origins in Chromium.

2022-10-31 13:17 UTC, schalkneethling commented on content/topics/what-is-a-web-browser/index.md
> +For example, when you type in 'www.google.com' and hit enter, the browser gets the necessary files (HTML, CSS, Javascript, Images and more) from Google's servers and paints up the page (rendering) wh
> Just a small grammatical suggestion. I think the last word 'with' needs to be removed.

Updated.

2022-10-31 13:19 UTC, schalkneethling commented on content/topics/what-is-a-web-browser/index.md
> +This article breaks down the different parts and features of a browser with simple explanations and images: [Internet Basics - Using a Web Browser](https://edu.gcfglobal.org/en/internetbasics/using-a
> I feel the article has more useful content besides just the video. I do agree with just linking to the page.

Ah, yes, I was not suggesting that we not link to the article. My suggestion was that we link to the article but also, embed the video on web://workbook. What do you think?

2022-10-31 13:25 UTC, schalkneethling commented
Hey @bharmalh, thank you for all your work here. Let me know when you have had a moment to address the feedback. I would love to get this one merged. 🚀

2022-10-31 13:26 UTC, schalkneethling commented
@bharmalh One thing to note, before making any changes locally, first do a pull from your branch, as there are some changes that were committed here and a merge of the latest from`main`.

2022-12-06 14:11 UTC, bharmalh commented
Hi,
Sincere apologies for the delayed response. I have made the suggested changes and pushed. Kindly review.
Thanks.

2022-12-17 15:07 UTC, schalkneethling approved these changes
Thanks, @bharmalh 🎉

2022-12-17 15:08 UTC, merged