24 adding ssl
The-Mycelium-Network/webworkbook pull request #60
Opened 2022-10-16 06:48 UTC by BlackNinjaCat86

2022-10-17 00:53 UTC, schalkneethling requested changes
Thanks, @BlackNinjaCat86 - A couple of recommendations and a requested change.

2022-10-17 00:53 UTC, schalkneethling commented on content/topics/protocols/index.md
> +* [Microsoft](https://learn.microsoft.com/en-us/windows/win32/dns/dns-servers)
This could cause a merge conflict with your other pull request to the DNS docs. I would recommend that you remove this section from this pull request.

2022-10-17 00:53 UTC, schalkneethling commented on content/topics/protocols/index.md
> +SSL uses cryptographic keys to encrypt information; a public key encrypts the data and a private key decrypts it.
I think we can dig a little deeper here. Perhaps there's a video on Youtube that can also help explain this a bit more? Code.org tends to have nice short little videos on these topics on Youtube.

2022-10-17 00:53 UTC, schalkneethling commented on content/topics/protocols/index.md
> +* [CsOonLine](https://www.csoonline.com/article/3246212/what-is-ssl-how-ssl-certificates-enable-encrypted-communication.html)
```suggestion
* [TechTarget](https://www.techtarget.com/searchsecurity/definition/Secure-Sockets-Layer-SSL)
* [CloudFlare](https://www.cloudflare.com/learning/ssl/what-is-ssl/)
* [CsOonLine](https://www.csoonline.com/article/3246212/what-is-ssl-how-ssl-certificates-enable-encrypted-communication.html)
```

2022-10-22 12:04 UTC, Rico-Smit requested changes

2022-10-22 12:04 UTC, Rico-Smit commented on content/topics/protocols/index.md
> +* [Microsoft](https://learn.microsoft.com/en-us/windows/win32/dns/dns-servers)
```suggestion
```

2022-10-22 12:55 UTC, Rico-Smit reviewed
Updated with new info

2022-10-22 12:58 UTC, BlackNinjaCat86 commented
I will be opening a new PR with new info

2022-10-22 12:58 UTC, closed without merging