adding SSL with updated info
The-Mycelium-Network/webworkbook pull request #67
Opened 2022-10-22 13:04 UTC by BlackNinjaCat86

I have updated the SSL protocol with new info.

2022-10-22 14:37 UTC, schalkneethling requested changes
Thank you for digging into this some more, @BlackNinjaCat86 :+1: I provided some more context and history we should also dig into. Thanks!

2022-10-22 14:37 UTC, schalkneethling commented on content/topics/protocols/index.md
> +{{< youtube id="ZghMPWGXexs&ab" title="SSL Encryption and decrytion" >}}
As mentioned on another pull request, perhaps reword this to something like:

```suggestion
{{< youtube id="ZghMPWGXexs&ab" title="A video explaining SSL encryption and decryption" >}}
```

2022-10-22 14:37 UTC, schalkneethling commented on content/topics/protocols/index.md
> +This is a networking protocol that keeps your internet connection secure and ensures that data being transfered remains private. This protocols' main use is securing the connection/communication betw
```suggestion
Secure socket layer (SSL) is a networking protocol that keeps your internet connection secure and ensures that the data being transferred remains private. This protocol's main use is securing the connection/communication between your browser and a web server. It does this by scrambling the data and making it impossible to read to anyone trying to intercept it. SSL uses cryptographic keys to encrypt information; a public key encrypts the data, and a private key decrypts it (making it readable). An SSL certificate enables websites to move from HTTP to HTTPS.
```

Seeing that we are mentioning SSL certificates, it would be helpful to dig into it a little bit more. https://www.cloudflare.com/learning/ssl/what-is-an-ssl-certificate/

This is a useful browser extension that would be good to mention. https://www.eff.org/https-everywhere

Also, SSL certificates used to be incredibly expensive and hard to come by. A non-profit called Let's Encrypt changed all of this and is a large part of why most, if not all, of the internet is now served over HTTPS. I would be good to also mention them and a little bit of the history behind it all. https://letsencrypt.org/about/

2022-10-22 14:45 UTC, BlackNinjaCat86 commented
@schalkneethling, all changes have been made 😄

2022-10-24 23:20 UTC, schalkneethling approved these changes
Thank you, @BlackNinjaCat86 🌮

2022-10-24 23:20 UTC, merged