Added HTTPS,HTTProtocol, part of #24
The-Mycelium-Network/webworkbook pull request #74
Opened 2022-11-01 08:18 UTC by carinadiesel-dev

Please give feedback, I was not sure if HTTPS needed some more info

2022-11-08 17:47 UTC, schalkneethling requested changes
Thank you for the hard work here, @carinadiesel-dev 🎉  Some items for you to address. Thanks.

2022-11-08 17:47 UTC, schalkneethling commented on content/topics/protocols/index.md
> +- [Cloudflare-UDP](https://www.cloudflare.com/learning/ddos/glossary/user-datagram-protocol-udp/)
For consistency:

```suggestion
- [MDN Web Docs: UDP](https://developer.mozilla.org/en-US/docs/Glossary/UDP)
- [Cloudflare: UDP](https://www.cloudflare.com/learning/ddos/glossary/user-datagram-protocol-udp/)
```

2022-11-08 17:47 UTC, schalkneethling commented on content/topics/protocols/index.md
> +- SFTP (SSH File Transfer Protocol), which runs over the SSH Protocol and provides encrypted data communication.
For consistency:

```suggestion
- FTP Secure (FTPS), which adds a security layer on top of FTP using cryptographic protocols like SSL or TLS;
- SSH File Transfer Protocol (SFTP) runs over the SSH Protocol and provides encrypted data communication.

```

2022-11-08 17:47 UTC, schalkneethling commented on content/topics/protocols/index.md
> +FTP Secure is used to securely transfer data between users, companies or clients. It's an extension of the File Transfer Protocol (FTP) which adds support for a security layer. FTPS uses cryptographi
> FTP Secure is used to securely transfer data between

Maybe we should rather say:

> FTP Secure is used to securely transfer data between computer systems.

2022-11-08 17:47 UTC, schalkneethling commented on content/topics/protocols/index.md
> +In a nutshell, the data gets encrypted before it's sent, preventing it from being intercepted and read by third parties. FTP make use of client certification and server identities when transferring t
```suggestion
In a nutshell, the data gets encrypted before it's sent, preventing it from being intercepted and read by third parties. FTPS uses client certification and server identities when transferring the data from point A to point B, and various security measures and encryption strategies are used to connect with foreign servers and verify authenticity before sending any data.

```

2022-11-08 17:47 UTC, schalkneethling commented on content/topics/protocols/index.md
> +HTTP and all extended protocols based on HTTP are established on the [request and response model](https://medium.com/@reemshakes/http-request-response-flow-for-dummies-a0f52af83af3),meaning the clien
```suggestion
HTTP and all extended protocols based on HTTP are established on the [request and response model](https://medium.com/@reemshakes/http-request-response-flow-for-dummies-a0f52af83af3), meaning the client sends a `request` to the server, and the server sends back a `response` if the request fails the response will be an error code. A well-known error code is 404 - Not Found. For the full list of HTTP error codes, click [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status)

```

2022-11-08 17:47 UTC, schalkneethling commented on content/topics/protocols/index.md
> +- [Microsoft Learn: DNS Servers](https://learn.microsoft.com/en-us/windows/win32/dns/dns-servers)
Whoops, this is duplicated.

2022-11-08 17:47 UTC, schalkneethling commented on content/topics/types-of-connections/index.md
> +!(https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.tech-faq.com%2Fdial-up-connection.html&psig=AOvVaw1aJbdUbuhccAm5R9-EBUw_&ust=1665823821490000&source=images&cd=vfe&ved=0CA0QjRxqFwoTCIjBpLur3_o
What was the intent of this? I think it is meant to be a link to tech-faq, but perhaps copied directly from a Google search results page?

2022-11-08 17:47 UTC, schalkneethling commented on content/topics/types-of-connections/index.md
> +### More Resources Info
I believe we use either `Reference` or `Additional reading`

2022-11-08 17:47 UTC, schalkneethling commented on content/topics/types-of-connections/index.md
> +# Broadband
We should only ever have a single H1 element i.e. `#`. I would make this:

```suggestion
## Broadband
```

And the next `###` and so forth.

2022-11-08 17:47 UTC, schalkneethling commented on content/topics/types-of-connections/index.md
> +According to [Enterprise Spectrum](https://enterprise.spectrum.com/support/faq/internet/how-does-fiber-internet-work.html) Fiber Internet provides Internet access using fiber-optic cable rather than
```suggestion
According to [Enterprise Spectrum](https://enterprise.spectrum.com/support/faq/internet/how-does-fiber-internet-work.html) Fiber Internet provides Internet access using a fiber-optic cable rather than traditional copper cable or satellite signals. Fiber-optic lines consist of up to hundreds of small strands of glass or plastic cables, each about 1/10th the size of a single human hair. Each fiber cable strand transmits data using pulses of light that travel at speeds approaching the speed of light.
```

2022-11-08 17:47 UTC, schalkneethling commented on content/topics/types-of-connections/index.md
> +!(https://media.geeksforgeeks.org/wp-content/uploads/Capture-86.png)
```suggestion
![we should provide some alt text for this image](https://media.geeksforgeeks.org/wp-content/uploads/Capture-86.png)
```

2022-11-08 17:47 UTC, schalkneethling commented on content/topics/types-of-connections/index.md
> +!(https://media.geeksforgeeks.org/wp-content/uploads/Capture-86.png)
Also, we should not link to a graphic like this as the site might not be OK with that. Perhaps we can find something similar on Wikipedia and download and serve it directly?

2022-11-08 17:47 UTC, schalkneethling commented on content/topics/types-of-connections/index.md
> +There are two types of DSL,namely Assymetric DSL (ADSL) and Symmetric DSL (SDSL).
```suggestion
There are two types of DSL, namely Assymetric DSL (ADSL) and Symmetric DSL (SDSL).
```

2022-11-08 17:47 UTC, schalkneethling commented on content/topics/types-of-connections/index.md
> +!(https://www.upwardbroadband.com/wp-content/uploads/2020/01/How-Cable-Internet-Works.png)
Same comment here as earlier about alt text and using images that are preferably in the public domain or CC0 (Creative commons)

2022-11-08 17:47 UTC, schalkneethling commented on content/topics/types-of-connections/index.md
> +{{< youtube id="hePLDVbULZc" title="How Wi-fi works" >}}
Was this intentional?

2022-11-08 17:47 UTC, schalkneethling commented on content/topics/types-of-connections/index.md
> +https://www.fcc.gov/general/types-broadband-connections
Are we using the speed-chart.png? I would prefer to instead create an HTML table and drop the last two columns. Let me know what you think.

2022-11-20 14:47 UTC, bpires requested changes
@schalkneethling I seized the opportunity to review all the internet protocols. As the previous ones were the result of PRs from me and @Rico-Smit, I believe, I took the liberty to accept some of your suggested changes, okay? 

@carinadiesel-dev I've added some suggestions to the ones Schalk made for HTTP and HTTPS, and I'll wait for your feedback! Great work, just minor details like style and consistency 😃 most reviews just need a "commit suggestion" (if agreed). Very few needs to be talked through, but we'll get there!

2022-11-20 14:47 UTC, bpires commented on content/topics/protocols/index.md
> +## What are protocols exactly?
Agreed, the "exactly" is an interesting resource in text, but it kinda feels that it would become after an introductory bit, often polemicizing... like: "Some people say this, some people say that. So, what are protocols exactly?"

2022-11-20 14:47 UTC, bpires commented on content/topics/protocols/index.md
> +## What are protocols exactly?
```suggestion
## What are protocols?

```

2022-11-20 14:47 UTC, bpires commented on content/topics/protocols/index.md
> +### POP3
```suggestion
### POP3 (Post Office Protocol 3)

```

Consistency.

2022-11-20 14:47 UTC, bpires commented on content/topics/protocols/index.md
> +### UDP
```suggestion
### UDP (User Datagram Protocol)

```

Title consistency.

2022-11-20 14:47 UTC, bpires commented on content/topics/protocols/index.md
> +### HTTP **Hyper Text Transfer Protocol**
```suggestion
### HTTP (Hyper Text Transfer Protocol)

```

Consistency.

2022-11-20 14:47 UTC, bpires commented on content/topics/protocols/index.md
> +HTTP is the protocol of the internet,it is responsible for communication between web severs and clients. It is simple and designed to be human readable. This protocol is also extensible,thanks to HTT
```suggestion
HTTP is the protocol of the internet and it is responsible for communication between web servers and clients. It is simple and designed to be human-readable. This protocol is also extensible, thanks to HTTP [headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers), it is easy to expand and experiment with.

```

2022-11-20 14:47 UTC, bpires commented on content/topics/protocols/index.md
> +HTTP is stateless,this means that each request that the server receives is independent and not linked to any prior requests.
```suggestion
HTTP is stateless, this means that each request that the server receives is independent and not linked to any prior requests.

```

2022-11-20 14:47 UTC, bpires commented on content/topics/protocols/index.md
> +### HTTPS
```suggestion
### HTTPS (Hyper Text Transfer Protocol Secure)

```

2022-11-20 14:47 UTC, bpires commented on content/topics/protocols/index.md
> +In corporate networks, SSH protocol can be used to guarantee secure access for users and allow issuing remote commands. A strong authentication protocol is also key for running automated processes an
```suggestion
In corporate networks, SSH protocol can be used to guarantee secure access for users and allow issuing of remote commands. A strong authentication protocol is also key for running automated processes and file transfers without risking an invasion or data breach.

```

2022-11-20 14:47 UTC, bpires commented on content/topics/protocols/index.md
> +- [SSH-SSH Academy](https://www.ssh.com/academy/ssh/protocol)
```suggestion
- [SSH Academy: SSH Protocol – Secure Remote Login and File Transfer](https://www.ssh.com/academy/ssh/protocol)

```

2022-11-20 14:47 UTC, bpires commented on content/topics/protocols/index.md
> +- [SFTP-SSH Academy](https://www.ssh.com/academy/ssh/protocol)
```suggestion
- [SSH Academy: SFTP File Transfer Protocol - get SFTP client & server](https://www.ssh.com/academy/ssh/sftp)

```

Wrong link.

2022-11-20 14:47 UTC, bpires commented on content/topics/protocols/index.md
> +### SSL **Secure Sockets Layer**
```suggestion
### SSL (Secure Sockets Layer)

```

2022-11-20 14:47 UTC, bpires commented on content/topics/protocols/index.md
> +- [TechTarget](htttps://www.techtarget.com/searchsecurity/definition/Secure-Sockets-Layer-SSL)
```suggestion
- [TechTarget: SSL (secure sockets layer)](https://www.techtarget.com/searchsecurity/definition/Secure-Sockets-Layer-SSL)

```

Too many t's ;)

2022-11-20 14:47 UTC, bpires commented on content/topics/protocols/index.md
> +- [CSoOnline](https://www.csoonline.com/article/3246212/what-is-ssl-how-ssl-certificates-enable-encrypted-communication.html)
```suggestion
- [CSoOnline: What is SSL? How SSL certificates enable encrypted communication](https://www.csoonline.com/article/3246212/what-is-ssl-how-ssl-certificates-enable-encrypted-communication.html)

```

2022-11-20 14:47 UTC, bpires commented on content/topics/protocols/index.md
> +- [CloudFlare](https://www.cloudflare.com/learning/ssl/what-is-ssl/)
```suggestion
- [CloudFlare: What is SSL? | SSL definition](https://www.cloudflare.com/learning/ssl/what-is-ssl/)

```

2022-11-20 14:47 UTC, bpires commented on content/topics/protocols/index.md
> +[OmniSecu Tutorials](https://www.omnisecu.com/tcpip/http-hypertext-transfer-protocol-request-response.php)
```suggestion
- [MDN Web Docs: An overview of HTTP](https://developer.mozilla.org/en-US/docs/Web/HTTP/Overview)
- [Traversy Media: HTTP Crash Course & Exploration](https://www.youtube.com/watch?v=iYM2zFP3Zn0&ab_channel=TraversyMedia)
- [OmniSecu Tutorials: Hypertext Transfer Protocol (HTTP) - Request and Response](https://www.omnisecu.com/tcpip/http-hypertext-transfer-protocol-request-response.php)

```

2022-11-20 14:47 UTC, bpires commented on content/topics/protocols/index.md
> +HTTPS is a secure version of the HTTP protocol that is encrypted and authenticated by the SSL/TLS protocol. This connection is secure thus allowing clients to safely exchange sensitive data with a se
```suggestion
HTTPS is a secure version of the HTTP protocol that is encrypted and authenticated by the SSL/TLS protocol. This connection is secure, thus allowing clients to safely exchange sensitive data with a server, like banking and credit card details.

```

2022-11-20 14:47 UTC, bpires commented on content/topics/protocols/index.md
> +[Cloudflare.com](https://www.cloudflare.com/en-gb/learning/ssl/what-is-https/)
```suggestion
- [SSL.com: What is HTTPS?](https://www.ssl.com/faqs/what-is-https/)
- [Tech Target: Hypertext Transfer Protocol Secure (HTTPS)](https://www.techtarget.com/searchsoftwarequality/definition/HTTPS)
- [Cloudflare: What is HTTPS?](https://www.cloudflare.com/en-gb/learning/ssl/what-is-https/)

```

2022-11-20 14:47 UTC, bpires commented on content/topics/protocols/index.md
> +### DNS **Domain Name System**
```suggestion
### DNS (Domain Name System)

```

2022-11-20 14:47 UTC, bpires commented on content/topics/protocols/index.md
> +- [Microsoft Learn: DNS Servers](https://learn.microsoft.com/en-us/windows/win32/dns/dns-servers)
```suggestion

```

2022-11-20 14:47 UTC, bpires commented on content/topics/protocols/index.md
> +## What are protocols exactly?
```suggestion
## What are protocols?

```

2022-11-20 14:52 UTC, bpires commented on content/topics/protocols/index.md
> +FTP Secure is used to securely transfer data between users, companies or clients. It's an extension of the File Transfer Protocol (FTP) which adds support for a security layer. FTPS uses cryptographi
```suggestion
FTP Secure is used to securely transfer data between computer systems. It's an extension of the File Transfer Protocol (FTP) which adds support for a security layer. FTPS uses cryptographic protocols like SSL (Secure Sockets Layer) or TLS (Transport Layer Security), although the former is now deprecated due to security vulnerabilities.

```

2022-12-19 22:30 UTC, closed without merging